import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/components/context/auth";
import { JobProvider } from "@/components/context/job";
import { UserApplicationProvider } from "@/components/context/userApplication";
import { Toaster } from "@/components/ui/toaster";
import { AdminProvider } from "@/components/context/admininfo";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <AdminProvider>
            <UserApplicationProvider>
              <JobProvider>{children}</JobProvider>
            </UserApplicationProvider>
          </AdminProvider>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
