import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/components/context/auth";
import { JobProvider } from "@/components/context/job";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <JobProvider>{children}</JobProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
